### ISSUE TITLE
New projects for authenticated users are missing the style.css file

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/thimble.webmaker.org#1168]
Getting this url: https://thimble.mozilla.org/projects/new?cacheBust=1444324560565

And Internal Server Error

**Comment by humphd** [comment]
Looks like db problems on prod:

```
     Oct 08 10:27:03 publish-webmaker-org-prod app/web.2: [2015-10-08T17:27:02.954Z] ERROR: publish.webmaker.org/3 on 31e71719-cb29-4ac2-9a9d-7a13093bdc01:  
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:      
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     req_id: 1444325222890:31e71719-cb29-4ac2-9a9d-7a13093bdc01:3:ifigtbxh:13072 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     request: { 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "path": "/projects", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "method": "post", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "headers": { 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "host": "publish-webmaker-org-prod.herokuapp.com", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "connection": "close", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "authorization": "token 388fc4aebf1e4fe4aed5a185d5f7b71dfeab92b3002d564fd5a46761d93468ab", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "cookie": "crumb=zSLR1_PRb4luha0ZPRzV550tKn8fu99jxsVvVhKxHix", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "accept": "application/json", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "content-type": "application/json", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "x-request-id": "0e9370d7-1de1-48e9-ae8b-bf97529b1f7b", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "x-forwarded-for": "54.144.204.192", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "x-forwarded-proto": "https", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "x-forwarded-port": "443", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "via": "1.1 vegur", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "connect-time": "2", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "x-request-start": "1444325222890", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "total-route-time": "0", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "content-length": "127" 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       } 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     } 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     response: { 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "payload": { 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "statusCode": 500, 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "error": "Internal Server Error", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         "message": "An internal server error occurred" 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       } 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     } 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     error: { 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "name": "error", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "length": 119, 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "severity": "ERROR", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "code": "42703", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "position": "25", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "file": "parse_target.c", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "line": "923", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "routine": "checkInsertTargets", 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:       "message": "insert into \"projects\" (\"client\", \"date_created\", \"date_updated\", \"description\", \"readonly\", \"tags\", \"title\", \"user_id\") values ($1, $2, $3, $4, $5, $6, $7, $8) returning \"id\" - column \"client\" of relation \"projects\" does not exist" 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     } 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     stack: error: insert into "projects" ("client", "date_created", "date_updated", "description", "readonly", "tags", "title", "user_id") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" - column "client" of relation "projects" does not exist 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at Connection.parseE (/app/node_modules/pg/lib/connection.js:539:11) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:366:17) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:105:22) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at TLSSocket.emit (events.js:107:17) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at readableAddChunk (_stream_readable.js:163:16) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at TLSSocket.Readable.push (_stream_readable.js:126:10) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:         at TCP.onread (net.js:538:20) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2: Debug: internal, implementation, error  
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     Error: Internal Server Error 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Object.exports.create (/app/node_modules/boom/lib/index.js:21:17) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Object.exports.internal (/app/node_modules/boom/lib/index.js:262:99) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Object.exports.badImplementation (/app/node_modules/boom/lib/index.js:298:23) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at module.exports.generateErrorResponse (/app/api/classes/errors.js:40:15) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at bound (domain.js:254:14) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at runBound (domain.js:267:12) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:503:31) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:577:18) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:693:14) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/main/async.js:15:14) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at Immediate.wrapped [as _onImmediate] (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
    Oct 08 10:27:03 publish-webmaker-org-prod app/web.2:     at processImmediate [as _immediateCallback] (timers.js:367:17) 
...
request_id=037d43aa-9a97-4d20-90dd-36699762cb2f fwd="54.144.204.192" dyno=web.1 connect=0ms service=312ms status=200 bytes=727 
    Oct 08 10:27:14 publish-webmaker-org-prod heroku/router: at=info method=POST path="/projects" host=publish-webmaker-org-prod.herokuapp.com request_id=d2a9dc68-2556-486f-bd90-a69e16b1fd3f fwd="54.144.204.192" dyno=web.2 connect=1ms service=127ms status=500 bytes=580 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2: [2015-10-08T17:27:14.217Z] ERROR: publish.webmaker.org/3 on 31e71719-cb29-4ac2-9a9d-7a13093bdc01:  
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:      
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     req_id: 1444325234093:31e71719-cb29-4ac2-9a9d-7a13093bdc01:3:ifigtbxh:13096 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     request: { 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "path": "/projects", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "method": "post", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "headers": { 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "host": "publish-webmaker-org-prod.herokuapp.com", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "connection": "close", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "authorization": "token 388fc4aebf1e4fe4aed5a185d5f7b71dfeab92b3002d564fd5a46761d93468ab", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "cookie": "crumb=zSLR1_PRb4luha0ZPRzV550tKn8fu99jxsVvVhKxHix", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "accept": "application/json", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "content-type": "application/json", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "x-request-id": "d2a9dc68-2556-486f-bd90-a69e16b1fd3f", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "x-forwarded-for": "54.144.204.192", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "x-forwarded-proto": "https", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "x-forwarded-port": "443", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "via": "1.1 vegur", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "connect-time": "1", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "x-request-start": "1444325234089", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "total-route-time": "0", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "content-length": "127" 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       } 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     } 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     response: { 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "payload": { 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "statusCode": 500, 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "error": "Internal Server Error", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         "message": "An internal server error occurred" 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       } 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     } 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     error: { 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "name": "error", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "length": 119, 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "severity": "ERROR", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "code": "42703", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "position": "25", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "file": "parse_target.c", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "line": "923", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "routine": "checkInsertTargets", 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:       "message": "insert into \"projects\" (\"client\", \"date_created\", \"date_updated\", \"description\", \"readonly\", \"tags\", \"title\", \"user_id\") values ($1, $2, $3, $4, $5, $6, $7, $8) returning \"id\" - column \"client\" of relation \"projects\" does not exist" 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     } 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     -- 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     stack: error: insert into "projects" ("client", "date_created", "date_updated", "description", "readonly", "tags", "title", "user_id") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" - column "client" of relation "projects" does not exist 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at Connection.parseE (/app/node_modules/pg/lib/connection.js:539:11) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:366:17) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:105:22) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at TLSSocket.emit (events.js:107:17) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at readableAddChunk (_stream_readable.js:163:16) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at TLSSocket.Readable.push (_stream_readable.js:126:10) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:         at TCP.onread (net.js:538:20) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2: Debug: internal, implementation, error  
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     Error: Internal Server Error 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Object.exports.create (/app/node_modules/boom/lib/index.js:21:17) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Object.exports.internal (/app/node_modules/boom/lib/index.js:262:99) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Object.exports.badImplementation (/app/node_modules/boom/lib/index.js:298:23) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at module.exports.generateErrorResponse (/app/api/classes/errors.js:40:15) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at bound (domain.js:254:14) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at runBound (domain.js:267:12) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:503:31) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:577:18) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:693:14) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/main/async.js:15:14) 
    Oct 08 10:27:14 publish-webmaker-org-prod heroku/router: at=info method=GET path="/projects/23994" host=publish-webmaker-org-prod.herokuapp.com request_id=a91d571d-58d9-46c7-be30-f3fed1da6cc9 fwd="54.144.204.192" dyno=web.2 connect=2ms service=365ms status=200 bytes=692 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at Immediate.wrapped [as _onImmediate] (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
    Oct 08 10:27:14 publish-webmaker-org-prod app/web.2:     at processImmediate [as _immediateCallback] (timers.js:367:17) 
    Oct 08 10:27:14 publish-webmaker-org-prod heroku/router: at=info method=GET path="/publishedProjects/75/publishedFiles/tar" host=publish-webmaker-org-prod.herokuapp.com request_id=e02b6f6a-cea3-44f7-b3e2-4e07d28892ae fwd="50.16.31.236" dyno=web.2 connect=1ms service=2140ms status=200 bytes=24605
```

cc @jbuck

**Comment by humphd** [comment]
We need to run a database migration on prod for @Pomax's change to the publish db.  @jbuck is doing now.

**Comment by humphd** [comment]
@jgmac1106 THANK YOU FOR REPORTING THIS!

**Comment by sedge** [comment]
Fixed!

**Comment by jgmac1106** [comment]
Thank you @sedge @humphd  @pomax and @jbuck

**Comment by jgmac1106** [comment]
Is new project supposed to come with only index file now? 

If so I would delete the css link and put in directions in code comments like javascript file
![newproject](https://cloud.githubusercontent.com/assets/10534566/10374713/a01f9df4-6dc2-11e5-9faf-842746514130.png)

**Comment by humphd** [comment]
No, that's something else we've seen randomly.  Re-opening.

**Comment by humphd** [comment]
The tarball we send from the node app is missing the `style.css` file, so this has to be some kind of server-side bug.  It only happens for authenticated users with a new project.

**Comment by jbuck** [comment]
@humphd Maybe related to your tarball generation changes?

**Comment by humphd** [comment]
@jbuck don't think so, because this is *only* done on Thimble's node app (i.e., the default new project for a Thimble user doesn't read from publish).  It has to be the Thimble node app, we're trying to find it now.

**Comment by jbuck** [comment]
Ahh, my apologies

**Comment by humphd** [comment]
No apology necessary, we need more theories.  We're baffled.

**Comment by jgmac1106** [comment]
I doubt this could have possible do anything but I was saving right when you pushed to production: 

![unnamed image 1](https://cloud.githubusercontent.com/assets/10534566/10376453/f523c614-6dcb-11e5-8363-b4d8d6344618.png)

**Comment by sedge** [comment]
This is a promise bug. Patch incoming...

**Comment by humphd** [comment]
Fixed by https://github.com/mozilla/publish.webmaker.org/commit/4313551b7a72b2b6353580e20b067dfa6b24fc07, long live @sedge.
